//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shellXamarin.Module.Navigation.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("shellXamarin.Module.Navigation.Resources.AppResources.ar", typeof(AppResources_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string navigation_tab_home {
            get {
                return ResourceManager.GetString("navigation.tab.home", resourceCulture);
            }
        }
        
        internal static string navigation_tab_settings {
            get {
                return ResourceManager.GetString("navigation.tab.settings", resourceCulture);
            }
        }
        
        internal static string navigation_menu_home {
            get {
                return ResourceManager.GetString("navigation.menu.home", resourceCulture);
            }
        }
        
        internal static string navigation_menu_settings {
            get {
                return ResourceManager.GetString("navigation.menu.settings", resourceCulture);
            }
        }
        
        internal static string navigation_menu_account {
            get {
                return ResourceManager.GetString("navigation.menu.account", resourceCulture);
            }
        }
        
        internal static string navigation_menu_login {
            get {
                return ResourceManager.GetString("navigation.menu.login", resourceCulture);
            }
        }
        
        internal static string navigation_menu_register {
            get {
                return ResourceManager.GetString("navigation.menu.register", resourceCulture);
            }
        }
        
        internal static string navigation_menu_logout {
            get {
                return ResourceManager.GetString("navigation.menu.logout", resourceCulture);
            }
        }
    }
}
