//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shellXamarin.Module.Account.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("shellXamarin.Module.Account.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string account_action_back {
            get {
                return ResourceManager.GetString("account.action.back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string account_action_login {
            get {
                return ResourceManager.GetString("account.action.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string account_cancel {
            get {
                return ResourceManager.GetString("account.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        internal static string account_form_country_invalid {
            get {
                return ResourceManager.GetString("account.form.country.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string account_form_country_placeholder {
            get {
                return ResourceManager.GetString("account.form.country.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        internal static string account_form_country_required {
            get {
                return ResourceManager.GetString("account.form.country.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is invalid.
        /// </summary>
        internal static string account_form_dob_invalid {
            get {
                return ResourceManager.GetString("account.form.dob.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string account_form_dob_placeholder {
            get {
                return ResourceManager.GetString("account.form.dob.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is requried.
        /// </summary>
        internal static string account_form_dob_required {
            get {
                return ResourceManager.GetString("account.form.dob.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalid.
        /// </summary>
        internal static string account_form_email_invalid {
            get {
                return ResourceManager.GetString("account.form.email.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string account_form_email_placeholder {
            get {
                return ResourceManager.GetString("account.form.email.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Required.
        /// </summary>
        internal static string account_form_email_required {
            get {
                return ResourceManager.GetString("account.form.email.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is invalid.
        /// </summary>
        internal static string account_form_firstname_invalid {
            get {
                return ResourceManager.GetString("account.form.firstname.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string account_form_firstname_placeholder {
            get {
                return ResourceManager.GetString("account.form.firstname.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is requried.
        /// </summary>
        internal static string account_form_firstname_required {
            get {
                return ResourceManager.GetString("account.form.firstname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Password invalid.
        /// </summary>
        internal static string account_form_invalid {
            get {
                return ResourceManager.GetString("account.form.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is invalid.
        /// </summary>
        internal static string account_form_lastname_invalid {
            get {
                return ResourceManager.GetString("account.form.lastname.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string account_form_lastname_placeholder {
            get {
                return ResourceManager.GetString("account.form.lastname.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is requried.
        /// </summary>
        internal static string account_form_lastname_required {
            get {
                return ResourceManager.GetString("account.form.lastname.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is invalid.
        /// </summary>
        internal static string account_form_mobileNumber_invalid {
            get {
                return ResourceManager.GetString("account.form.mobileNumber.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number.
        /// </summary>
        internal static string account_form_mobileNumber_placeholder {
            get {
                return ResourceManager.GetString("account.form.mobileNumber.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is required.
        /// </summary>
        internal static string account_form_mobileNumber_required {
            get {
                return ResourceManager.GetString("account.form.mobileNumber.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News letter.
        /// </summary>
        internal static string account_form_newsletter_placeholder {
            get {
                return ResourceManager.GetString("account.form.newsletter.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News letter requried.
        /// </summary>
        internal static string account_form_newsletter_required {
            get {
                return ResourceManager.GetString("account.form.newsletter.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string account_form_password_placeholder {
            get {
                return ResourceManager.GetString("account.form.password.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Required.
        /// </summary>
        internal static string account_form_password_required {
            get {
                return ResourceManager.GetString("account.form.password.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is required.
        /// </summary>
        internal static string account_form_state_invalid {
            get {
                return ResourceManager.GetString("account.form.state.invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string account_form_state_placeholder {
            get {
                return ResourceManager.GetString("account.form.state.placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string account_login_title {
            get {
                return ResourceManager.GetString("account.login.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        internal static string account_ok {
            get {
                return ResourceManager.GetString("account.ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string account_register_title {
            get {
                return ResourceManager.GetString("account.register.title", resourceCulture);
            }
        }
    }
}
