//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shellXamarin.Module.Account.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("shellXamarin.Module.Account.Resources.AppResources.ar", typeof(AppResources_ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string account_login_title {
            get {
                return ResourceManager.GetString("account.login.title", resourceCulture);
            }
        }
        
        internal static string account_action_login {
            get {
                return ResourceManager.GetString("account.action.login", resourceCulture);
            }
        }
        
        internal static string account_action_update {
            get {
                return ResourceManager.GetString("account.action.update", resourceCulture);
            }
        }
        
        internal static string account_register_title {
            get {
                return ResourceManager.GetString("account.register.title", resourceCulture);
            }
        }
        
        internal static string account_edit_title {
            get {
                return ResourceManager.GetString("account.edit.title", resourceCulture);
            }
        }
        
        internal static string account_action_back {
            get {
                return ResourceManager.GetString("account.action.back", resourceCulture);
            }
        }
        
        internal static string account_form_header_personal {
            get {
                return ResourceManager.GetString("account.form.header.personal", resourceCulture);
            }
        }
        
        internal static string account_form_header_location {
            get {
                return ResourceManager.GetString("account.form.header.location", resourceCulture);
            }
        }
        
        internal static string account_form_email_placeholder {
            get {
                return ResourceManager.GetString("account.form.email.placeholder", resourceCulture);
            }
        }
        
        internal static string account_form_email_required {
            get {
                return ResourceManager.GetString("account.form.email.required", resourceCulture);
            }
        }
        
        internal static string account_form_email_invalid {
            get {
                return ResourceManager.GetString("account.form.email.invalid", resourceCulture);
            }
        }
        
        internal static string account_form_password_placeholder {
            get {
                return ResourceManager.GetString("account.form.password.placeholder", resourceCulture);
            }
        }
        
        internal static string account_form_password_required {
            get {
                return ResourceManager.GetString("account.form.password.required", resourceCulture);
            }
        }
        
        internal static string account_form_invalid {
            get {
                return ResourceManager.GetString("account.form.invalid", resourceCulture);
            }
        }
        
        internal static string account_cancel {
            get {
                return ResourceManager.GetString("account.cancel", resourceCulture);
            }
        }
        
        internal static string account_ok {
            get {
                return ResourceManager.GetString("account.ok", resourceCulture);
            }
        }
        
        internal static string account_form_firstname_placeholder {
            get {
                return ResourceManager.GetString("account.form.firstname.placeholder", resourceCulture);
            }
        }
        
        internal static string account_form_firstname_required {
            get {
                return ResourceManager.GetString("account.form.firstname.required", resourceCulture);
            }
        }
        
        internal static string account_form_firstname_invalid {
            get {
                return ResourceManager.GetString("account.form.firstname.invalid", resourceCulture);
            }
        }
        
        internal static string account_form_lastname_placeholder {
            get {
                return ResourceManager.GetString("account.form.lastname.placeholder", resourceCulture);
            }
        }
        
        internal static string account_form_lastname_required {
            get {
                return ResourceManager.GetString("account.form.lastname.required", resourceCulture);
            }
        }
        
        internal static string account_form_lastname_invalid {
            get {
                return ResourceManager.GetString("account.form.lastname.invalid", resourceCulture);
            }
        }
        
        internal static string account_form_dob_placeholder {
            get {
                return ResourceManager.GetString("account.form.dob.placeholder", resourceCulture);
            }
        }
        
        internal static string account_form_dob_required {
            get {
                return ResourceManager.GetString("account.form.dob.required", resourceCulture);
            }
        }
        
        internal static string account_form_dob_invalid {
            get {
                return ResourceManager.GetString("account.form.dob.invalid", resourceCulture);
            }
        }
        
        internal static string account_form_newsletter_placeholder {
            get {
                return ResourceManager.GetString("account.form.newsletter.placeholder", resourceCulture);
            }
        }
        
        internal static string account_form_newsletter_required {
            get {
                return ResourceManager.GetString("account.form.newsletter.required", resourceCulture);
            }
        }
    }
}
